name: Java CI with Maven on Linux

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - java: 11
            additional-maven-args: >
              -Pcoveralls
              -DrepoToken=$COVERALLS_REPO_TOKEN 
              -DpullRequest=${{github.event.pull_request.number}}
              org.pitest:pitest-maven:mutationCoverage
          - java: 17
            additional-maven-args: >
              -Pjacoco
              sonar:sonar
              -Dsonar.organization=lorenzocorbinelli
              -Dsonar.projectKey=LorenzoCorbinelli_AST-project
              -Dsonar.host.url=https://sonarcloud.io

    name: Build with Java ${{matrix.java}}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK ${{matrix.java}}
      uses: actions/setup-java@v1
      with:
        java-version: ${{matrix.java}}
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2
          ~/.sonar/cache
        key: ${{runner.os}}-m2-${{hashFiles('**/pom.xml', '**/*.yml')}}
        restore-keys: ${{runner.os}}-m2-
    - name: Build with Maven
      run: xvfb-run mvn verify ${{matrix.additional-maven-args}}
      env:
        COVERALLS_REPO_TOKEN: ${{secrets.COVERALLS_TOKEN}}
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
      working-directory: com.corbinelli.lorenzo.swimming
    - name: Archive PIT report
      uses: actions/upload-artifact@v2
      with: 
        name: PIT-report
        path: '**/target/pit-reports'
        